name = "BaytesInference"
uuid = "4ed8d1ce-aa1e-45bc-907d-4d37aaa2bb0b"
authors = ["Patrick Aschermayr <p.aschermayr@gmail.com>"]
version = "0.1.0"

[compat]
julia = "1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
